Rename Topics to Thematic Areas
NextGeoss/ckanext-grouphierarchy pull request #2
Opened 2019-09-05 11:58 UTC by georgiana-b

Together with https://github.com/NextGeoss/ckanext-nextgeoss/pull/103 solves https://github.com/NextGeoss/nextgeoss-catalogue-issues/issues/30.

Also added some documentation about the group parameters used in this plugin.

2019-09-27 07:01 UTC, JGulic requested changes
I've only pulled the changes from this extension locally and the title of the Topic was not shown in the about page. With the other changes on ckanext-nextgeoss it works, and the title is shown.
But let's move the name variable on top of the page, just so we have all the changes that affect this extension in it.

2019-09-27 07:01 UTC, JGulic commented on ckanext/grouphierarchy/templates/group/about.html
> +      {% set name = c.group_dict.title %}
setting the name variable inside the block causes the Title not to be shown on the Topic about page. Move it on the top, where the group variable is set.

2019-09-27 12:04 UTC, georgiana-b commented
@JGulic Moved `name` at the top of the template as requested. Feel free to merge if you think it's alright.

2019-10-16 09:32 UTC, JGulic approved these changes
ACK

2019-10-16 09:32 UTC, merged